### ISSUE TITLE
Not getting action for button inside SwipeCard to swipe the card

### ISSUE THREAD

**Issue by nainaghormare** [mac-gallagher/Shuffle#10]
All swipe actions work perfectly if buttons are outside the SwipeCard, but if button is inside the SwipeCard then the target is never called.

**Comment by mac-gallagher** [comment]
Can you please provide a link to your code? Guessing it is a problem with setting `isUserInteractionEnabled` to `true`/`false` on the correct subviews

**Comment by nainaghormare** [comment]
https://github.com/nainaghormare/SwipeCards

Please check "WaitingViewController"

**Comment by mac-gallagher** [comment]
Not sure by just looking at `WaitingViewController`. I suggest analyzing your view hierarchy and making sure that every view in front of your button has user interaction _disabled_.

By the way, I noticed you're not using the `contentView` variable as instructed in the README

**Comment by mac-gallagher** [comment]
Closing this since this thread has been inactive for 7 days. Feel free to reopen if the problem persists.
