### ISSUE TITLE
Add deleteCards: method

### ISSUE THREAD

**Issue by mac-gallagher** [mac-gallagher/Shuffle#103]

**Comment by wfgilman** [comment]
This and https://github.com/mac-gallagher/Shuffle/issues/96 would be super helpful. Here's the use case: I have a stack of cards that I want to dynamically filter. Say I have a 50 card stack, I swipe through 10 cards, discarding them. I then apply a filter which eliminates to 20 cards and reduces the remaining stack from 40 to 20. I swipe through 5 more cards, leaving 15 in the stack. I then remove the filter and the 20 filtered cards are added back to the stack, totaling 25.

I think this can be accomplished using the `deleteCardAtIndex` and `insertCardAtIndex`.
