### ISSUE TITLE
Header not precised in the README

### ISSUE THREAD

**Issue by Anybowdy** [mac-gallagher/Shuffle#110]
I downloaded the library.
I tried to use it but Xcode did not recognized SwipeCard.
It was not written on the README: please let the users know they need to import Shuffle_iOS in order to use the library

Thank you

**Comment by mac-gallagher** [comment]
This is something that is generally understood when it comes to importing external libraries. But sure, I will add something

**Comment by Anybowdy** [comment]
Yes thank you ! By the way the library is impressively well implemented. Good job !

**Comment by mac-gallagher** [comment]
Thank you 😄 Updated README here #111
