### ISSUE TITLE
Make some extra space at the top :help wanted:

### ISSUE THREAD

**Issue by LoopingLouieX** [mac-gallagher/Shuffle#20]
Hi all,
first I want to thank you very much for that really great work!
I am currently struggling with the layout of the card + footer.
What I want to do is to add some additional buttons at the top of the view.
But to do this I have to change the height of the picture to make some extra space available at the top.
Unfortunately I am unable to find the right parameter to handle this without changing additional things like footer height, picture width..
Can anyone help me ?
Thanks!

**Comment by mac-gallagher** [comment]
In your `SwipeCard` subclass, you should be providing the `content` variable - this is where your custom view should go. Your custom view can have any layout, so this does not sound like an issue with the framework.

**Comment by LoopingLouieX** [comment]
Thank you very much for that help and changing the label tag!
Well, i've tried it for hours now but without success (more familiar with storyboards till now).
Maybe you can explain that to me with a more detailed code sample if you have a minute sometime.
Really appreciate your help on this!

**Comment by mac-gallagher** [comment]
Is your problem just programmatic layout? If so, I suggest googling. There are lots of helpful articles on this

**Comment by LoopingLouieX** [comment]
I don't think the problem is with the programmatic layout..i get this done in a sample project.
It's rather that I don't understand the exact implementation here.
```
let containerView = UIView() --> understand
let mySubview = UIView() --> understand
```

That's where I struggle and getting the errors because from what is coming the "container." ?
`container` is nowhere declared.
```
container.addSubview(mySubview)
// some layout
```

**Comment by mac-gallagher** [comment]
There was a typo: `container` should be replaced with `containerView`, sorry

**Comment by mac-gallagher** [comment]
The implementation is that you have to provide the `content` view for each card yourself. All of your custom subviews should be on the `content` you provide. 

Please take a closer look at the example project.
