### ISSUE TITLE
Stack At Top

### ISSUE THREAD

**Issue by maasim94** [mac-gallagher/Shuffle#21]
Can we have stack showing at top? 
one workaround i have considered is to add artificially created stack like in following picture. but do have some better way to handle that?
also i have to use this as part of cell for UITableView, do you think it can create adverse effect?

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-22 at 13 27 24](https://user-images.githubusercontent.com/8789336/67273701-0671b180-f4d0-11e9-9802-96c823289458.png)

**Comment by mac-gallagher** [comment]
There is currently no way to have a custom card stack layout. I have opened #22 requesting this feature

**Comment by mac-gallagher** [comment]
The card stack should be fine in a tableview cell
