### ISSUE TITLE
Project can not be archived due to duplicate issue

### ISSUE THREAD

**Issue by maasim94** [mac-gallagher/Shuffle#24]
Project compiles well while debugging on simulator or phone but while compiling getting following issue

>  Unexpected duplicate tasks:
> 1) Target 'Shuffle-iOS' (project 'Pods') has copy command from ‘App Path/Pods/Shuffle-iOS/Sources/Shuffle.plist' to 'Library/Developer/Xcode/DerivedData/IAGeneralApp-arlhwwyhekielgcemsylmtysvpga/Build/Intermediates.noindex/ArchiveIntermediates/IAGeneralApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Shuffle_iOS.framework/Shuffle.plist'
> 2) Target 'Shuffle-iOS' (project 'Pods') has copy command from 'App Path/Pods/Shuffle-iOS/Sources/Shuffle.plist' to '/Library/Developer/Xcode/DerivedData/IAGeneralApp-arlhwwyhekielgcemsylmtysvpga/Build/Intermediates.noindex/ArchiveIntermediates/IAGeneralApp/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Shuffle_iOS.framework/Shuffle.plist'

Please note that when I archived using legacy build system it archived successfully, there is some compatibility issue with new build system

**Comment by mac-gallagher** [comment]
Can you please provide details steps to reproduce this? I just did a fresh clone and could not reproduce this on Xcode 11.

**Comment by maasim94** [comment]
@mac-gallagher 
1. create simple project.
2. add dependency via cocoa pods 
3. try to archive project.

you'll get the issue. 
I have also uploaded sample project using library.

[Test.zip](https://github.com/mac-gallagher/Shuffle/files/3771488/Test.zip)

**Comment by mac-gallagher** [comment]
Thanks for the sample project. It looks like the `.plist` file was getting included in the pod install. I fixed it with the latest pod version bump. Let me know if the issue still persists.
