### ISSUE TITLE
Won't compile with SPM

### ISSUE THREAD

**Issue by jerometonnelier** [mac-gallagher/Shuffle#38]
**Describe the bug**
I imported the latest Shuffle framework with the Swift Package Manager and I get several errors like "Use of undeclared type 'CGRect'" or "Use of undeclared type 'CGFloat'", which makes sense since CGStuff is in CoreGraphics, not in Foundation. Am I missing something with the SPM ? Thanks for your help ;-)

**To Reproduce**
Add the dependency for Shuffle and compile

**Expected behavior**
The code should compile

**Screenshots**
![Uploading Capture d’écran 2020-03-25 à 15.15.01.png…]()

**Additional context**

**Comment by mac-gallagher** [comment]
Ack, thanks for opening this issue @jerometonnelier. Turns out the fix is to import `UIKit` instead of `Foundation`. Opening a pull request now, thanks!

**Comment by jerometonnelier** [comment]
Awesome, thanks ;-) I manually imported the library and did the UIKit replacement, but I didn't know if it was an issue from the SPM or Xcode or just me ;-) Thanks.

**Comment by jerometonnelier** [comment]
Do you know when you will release the fix for SPM? Thanks ;-)

**Comment by mac-gallagher** [comment]
The change should already be in master. Let me know if you are able to build!

**Comment by jerometonnelier** [comment]
Nope, still the same issue from the spm :-/ Maybe I should get the package from master instead of the tagged version ?

**Comment by mac-gallagher** [comment]
Whoops, forgot to tag the new version. How about now?

**Comment by katanai** [comment]
Hi y'all, I can't build. I get this error: "UIKit is not available when building for macOS. Consider using `#if !os(macOS)` to conditionally import this framework." Help?

**Comment by mac-gallagher** [comment]
@katanai This library isn't supported on MacOS
