### ISSUE TITLE
Using Shuffle in UITableView/UICollectionView

### ISSUE THREAD

**Issue by andre991** [mac-gallagher/Shuffle#56]
**Describe the bug**
TableView and CollectionView don't scroll vertically if the shuffle is in any cell.

**To Reproduce**
Add SwipeCardStack inside TableViewCell/CollectionViewCell and scroll tableView vertically.

**Expected behavior**
If I chose to move horizontally, Shuffle don't be able to scroll vertically.

**Comment by mac-gallagher** [comment]
Hey @andre991! Thanks for reporting this issue, I will work on publishing a fix. In the meantime, you can try the following: for each `SwipeCard`, set `card.panGestureRecognizer.delegate = yourViewController` and conform your view controller to the `UIGestureRecognizerDelegate` protocol. You can write

```swift
func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
    guard let panGestureRecognizer = gestureRecognizer as? UIPanGestureRecognizer else { return true }
    let velocity = panGestureRecognizer.velocity(in: view)
    return abs(velocity.x) > abs(velocity.y) // return true only if pan gesture is more horizontal than vertical
  }
```

Let me know if that solves your issue for now. I will let you know once the actual fix is out!

**Comment by andre991** [comment]
Hi @mac-gallagher, thanks for this solution!!! Worked perfectly!

This framework is awesome!!

Congratulations! 👏🏻👏🏻👏🏻👏🏻
Have a nice day.

#StayHome

**Comment by mac-gallagher** [comment]
Hey @andre991 - added support for this in [version 0.2.2](https://github.com/mac-gallagher/Shuffle/releases/tag/v0.2.2).

Cheers!
Mac

**Comment by mac-gallagher** [comment]
FYI @andre991, updated the solution a bit here #69 . The previous implementation with delegates was kind of awkward
