### ISSUE TITLE
Crash appears after SwipeCardStack reloadData()

### ISSUE THREAD

**Issue by kupriknikita** [mac-gallagher/Shuffle#58]
Index after reload is 1, instead of 0

**Comment by mac-gallagher** [comment]
Please provide steps to reproduce

**Comment by kupriknikita** [comment]
Hi, okay, I have one SwipeCardStack and also I have Int variable "currentIndex = 0" with didSet, I incrementing it in `func cardStack(_ cardStack: SwipeCardStack, didSwipeCardAt index: Int, with direction: SwipeDirection) {} `, when "currentIndex = cards.count" I calling reload data in the stack and use him again with new UI data in SwipeCardStack, but index in `func cardStack(_ cardStack: SwipeCardStack, didSwipeCardAt index: Int, with direction: SwipeDirection) {} ` becomes to 1 after reloading, instead of 0,  and I have "Fatal error: Index out of range" in 233 line of SwipeCardStack.swift, sorry for my English

**Comment by mac-gallagher** [comment]
Do you mean to check `currentIndex = cards.count -1`? The `index`  in the `didSwipeCardAt ` method refers to the index you provided in the `cardForIndexAt` method. What do you `SwipeCardStackDataSource` methods look like?

**Comment by mac-gallagher** [comment]
Also, what version are you using? if you installed via cocoapods, this will be in your `Podfile.lock`

**Comment by kupriknikita** [comment]
```
private var cardIndex: Int = 0 {
        didSet {
            stepTitleLabel.text = "\(cardIndex)/\(words.count)"

            if stepBackground.isHidden {
                progressView.progress += Float(1) / Float(words.count)
                if cardIndex == words.count {
                    openGameResults()
                }
            }

            if cardIndex == words.count {
                cardIndex = 0
                stepBackground.isHidden = true
                progressView.isHidden = false
                rememberCardStack.reloadData()
            }
        }
    }
```

```
func cardStack(_ cardStack: SwipeCardStack, didSwipeCardAt index: Int, with direction: SwipeDirection) {
        cardIndex += 1
        print("didSwipeCardAt: \(index)")
    }

    func cardStack(_ cardStack: SwipeCardStack, cardForIndexAt index: Int) -> SwipeCard {
        let word = Array(words)[index]
        print("cardForIndexAt: \(index)")
        let model = CardViewModel(word: word.key,
                                  incorrectFirstWord: incorrectFirstWords[index],
                                  incorrectSecondWord: incorrectSecondWords[index],
                                  translation: word.value,
                                  isRemember: progressView.isHidden)
        return CardView(model: model)
    }

    func numberOfCards(in cardStack: SwipeCardStack) -> Int {
        return words.count
    }
```
cardForIndexAt: 0
cardForIndexAt: 1
didSwipeCardAt: 0
cardForIndexAt: 2
didSwipeCardAt: 1
cardForIndexAt: 3
didSwipeCardAt: 2
cardForIndexAt: 4
didSwipeCardAt: 3
cardForIndexAt: 0
cardForIndexAt: 1
didSwipeCardAt: 4
cardForIndexAt: 2
didSwipeCardAt: 1
cardForIndexAt: 3

**Comment by mac-gallagher** [comment]
It sounds like you are trying to reload a new stack of cards once the current stack is depleted. Why not just add your `reloadData` call to the `didSwipeAllCards` delegate method?

**Comment by kupriknikita** [comment]
I just used now reload in `didSwipeAllCards` and it's work correctly, I didn't notice the existence of this method

**Comment by kupriknikita** [comment]
Thank you!

**Comment by mac-gallagher** [comment]
No problem - glad I could help!
