### ISSUE TITLE
Do not dispose cards, instead shift on swipe

### ISSUE THREAD

**Issue by m42e** [mac-gallagher/Shuffle#59]
**Is your feature request related to a problem? Please describe.**
I would like to do something like memorise the order of cards. Therefore it would be good to disable disposal and just send them to the back.

**Describe the solution you'd like**
An option to disable the disposal.

**Describe alternatives you've considered**
Re-adding the card when getting notified to is has been swiped out. But this will break the undo. and make the handling somehow wired.

**Comment by mac-gallagher** [comment]
@m42e it sounds like you can just use the `shift` method on `SwipeCardStack` to accomplish this

**Comment by mac-gallagher** [comment]
Hi @m42e. I have been thinking about this, and I don't think this I will add this feature to `Shuffle`. The essence of the card stack is to dispose of cards once swiped.

It sounds like you are better off using a `UICollectionView` with a custom `UICollectionViewFlowLayout`. Something like this library here: https://github.com/amirdew/CollectionViewPagingLayout (the example project on this one is really cool!)

Mac

**Comment by m42e** [comment]
@mac-gallagher Fine for me. Thanks for the hint to the library. It might have what I wanted.
