### ISSUE TITLE
Property topCardIndex isn't updated immediately

### ISSUE THREAD

**Issue by akirichek** [mac-gallagher/Shuffle#71]
After I swiped a card the method `func cardStack(_ cardStack: SwipeCardStack, didSwipeCardAt index: Int, with direction: SwipeDirection)` of `SwipeCardStackDelegate` is called. 

And printing `topCardIndex` property of `SwipeCardStack` object there still returns `0`, however, it just has been swiped, so index `1` expected.

**Comment by mac-gallagher** [comment]
Hey @akirichek, I have a fix up here #72 . Do you mind testing it for your project? Thanks

**Comment by akirichek** [comment]
Hey @mac-gallagher , I have checked and approved the PR. Works well for me. Thanks

**Comment by lukicmarko** [comment]
I'm using the lastest version from master branch and having the same issue.
The library always returns 0 for index and 1 for cardStack.topCardIndex in the method:
```
    func cardStack(_ cardStack: SwipeCardStack, didSwipeCardAt index: Int, with direction: SwipeDirection) {

```
