### ISSUE TITLE
Can multiple SwipeCardStack be used in the same project?

### ISSUE THREAD

**Issue by Liandas** [mac-gallagher/Shuffle#77]
**Is your feature request related to a problem? Please describe.**
I tried to use multiple SwipeCardStack in the same project. It worked in the first one, but when I go to second one, It lost the first stack statuses. CardStackStateManager is shared (Singleton). 

**Describe the solution you'd like**
There is a convenience init function but it is not public. 

Are there any way to support multiple SwipeCardStack?

**Comment by mac-gallagher** [comment]
Yikes, this is definitely a bug. Thanks for opening this issue @Liandas, I will try to put up a fix over the weekend.

Mac

**Comment by mac-gallagher** [comment]
^ @Liandas let me know if this change works for you!
