### ISSUE TITLE
isUserInteractionEnabled does not work for SwipeCardStack

### ISSUE THREAD

**Issue by kupriknikita** [mac-gallagher/Shuffle#86]

**Comment by mac-gallagher** [comment]
Can you please be more specific?

**Comment by mac-gallagher** [comment]
@kupriknikita if you wish to disable interaction completely on the card stack, you can set 
```
cardStack.shouldRecognizeHorizontalDrag = false
cardStack.shouldRecognizeVerticalDrag = false
```

**Comment by kupriknikita** [comment]
This does not work completely, if you swipe on the map many times, it will still swipe

**Comment by mac-gallagher** [comment]
@kupriknikita please create a new issue request with the bug report template and fill out the details on this bug there
