### ISSUE TITLE
Is it possible to remove the ButtonStackView ?

### ISSUE THREAD

**Issue by LoopingLouieX** [mac-gallagher/Shuffle#93]
Hi,
is it possible to remove the ButtonStackView with the all the buttons in there ?
So that the content view(+footer) is filling out the whole screen automatically?
Thanks!

**Comment by mac-gallagher** [comment]
@LoopingLouieX yes it is possible, but I will not be making these changes as part of the library. You can simply just delete the `ButtonStackView` and set the constraints of the card stack to the bottom of the screen
